const { Book } = require('../models');

const bookdata = [
  {
    bookName: 'Do Hard Things: Why We Get Resilience Wrong and the Surprising Science of Real Toughness',
    author: 'Steve Magness',
    yearPublish: 2022,
    isbn: '978-0-06-309861-9',
    rentalPrice: 15.99,
    subject: 'social science',
    course: 'psychology',
    bookcoverURL: "http://books.google.com/books/content?id=m4KmzgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    available: true,
    owner_id: 1,
  },
  {
    bookName: 'Math with Bad Drawings: Illuminating the Ideas That Shape Our Reality',
    author: "Ben Orlin",
    yearPublish: 2018,
    isbn: '978-0-316-50903-9',
    rentalPrice: 10.99,
    subject: 'math',
    course: 'modern geometry',
    bookcoverURL: "http://books.google.com/books/content?id=UbzgtAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    available: true,
    owner_id: 2,
  },
  {
    bookName: 'College Algebra',
    author: "Julie Miller",
    yearPublish: 2016,
    isbn: '9780077836344',
    rentalPrice: 271.81,
    subject: 'math',
    course: 'college algebra',
    bookcoverURL: "http://books.google.com/books/content?id=wZW_oQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    available: true,
    owner_id: 2,
  },
  {
    bookName: 'Glencoe Algebra 1, Common Core edition',
    author: "McGraw Hill",
    yearPublish: 2012,
    isbn: '978-0076639236',
    rentalPrice: 3.14,
    subject: 'math',
    course: 'algebra 1',
    bookcoverURL: "http://books.google.com/books/content?id=jV6mlgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    available: true,
    owner_id: 2,
  },
  {
    bookName: 'Explorations: An Introduction To Astronomy',
    author: "Thomas Arny",
    yearPublish: 2005,
    isbn: '9780072509854',
    rentalPrice: 9.81,
    subject: 'science',
    course: 'astronomy',
    bookcoverURL: "http://books.google.com/books/content?id=apkKAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    available: false,
    owner_id: 1,
  },
  {
    bookName: 'Chemistry: The Central Science',
    author: "Theodore Brown",
    yearPublish: 2018,
    isbn: '978-0134414232',
    rentalPrice: 6.02,
    subject: 'science',
    course: 'chemistry',
    bookcoverURL: "http://books.google.com/books/content?id=NBtOvgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    available: true,
    owner_id: 3,
  },
  {
    bookName: 'Psychology',
    author: "David Myers",
    yearPublish: 2011,
    isbn: '978-1429261784',
    rentalPrice: 129.00,
    subject: 'Psychology',
    course: 'Psychology',
    bookcoverURL: "http://books.google.com/books/content?id=vi-xZwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    available: true,
    owner_id: 3,
  },
];

const seedBook = async () => 
await Book.bulkCreate(bookdata, {
});


module.exports = {seedBook};
